### ISSUE TITLE
"Safari cannot open the page because it could not establish a secure connection to the server."

### ISSUE THREAD

**Issue by ShawkMusic** [H-M-H/Weylus#96] opened 2021-06-22 08:02 UTC
When I try to open the link on Safari on iPadOS 13.3, It gives this message: "Safari cannot open the page because it could not establish a secure connection to the server."

I noticed it automatically redirects me to the HTTPS website even when I explicitly remove it from the link myself. Could that be why?

**Comment by H-M-H** [comment] 2021-06-22 10:19
Yes, this is most likely the reason. As Weylus is only intended to be used on local networks you trust, there is no encryption and only plain http is supported. This means you somehow need to find out how to prevent Safari from redirecting you to https.

**Comment by H-M-H** [comment] 2021-06-28 12:57
Closing for now as I could not reproduce this behaviour, if you have found a fix please let others know here.

**Closed by H-M-H** 2021-06-28 12:57 UTC
