### ISSUE TITLE
Video feed is so slow

### ISSUE THREAD

**Issue by abdalazizrashid** [H-M-H/Weylus#56] opened 2020-12-01 22:46 UTC
The input feed speed is fine but the video feed is slow.
I'm using i3 and Ipad pro 12.9.

**Comment by H-M-H** [comment] 2020-12-02 22:22
It's possible your system is just too slow at video encoding, you could try to open Weylus' webpage on another device or on your computer itself and check if the video is still slow. What's you screen resolution, have you tried selecting a window and making it smaller, do you have problems then too?

**Comment by abdalazizrashid** [comment] 2020-12-05 21:40
My screen resolution is 3840 x 2160 and even reducing the resolution doesn't really solve the problem.

**Comment by H-M-H** [comment] 2020-12-07 00:21
Please check if the latest build has the same issue: https://github.com/H-M-H/Weylus/suites/1611530425/artifacts/29502840

**Comment by abdalazizrashid** [comment] 2020-12-07 18:55
Yeah, still laggy I also noticed there is this error
```
[AVHWDeviceContext @ 0x7f456c001a40] libva: /usr/lib/dri/i965_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x7f456c001a40] Failed to initialise VAAPI connection: -1 (unknown libva error).
[h264_nvenc @ 0x7f456c002240] InitializeEncoder failed: invalid param (8): Invalid Level.
[libx264 @ 0x7f456c031600] MB rate (32400000) > level limit (16711680)
```

**Comment by H-M-H** [comment] 2021-02-11 00:12
The latest build does some down scaling now, if you are still interested please give it a try: https://github.com/H-M-H/Weylus/actions/runs/556217800#artifacts

**Comment by braunbearded** [comment] 2021-02-17 21:37
In case @abdalazizrashid didn't test this new version, I did. It runs considerably smother without any noticeable quality lost. I had some issues earlier which I sadly can't reproduce anymore.

**Comment by abdalazizrashid** [comment] 2021-02-17 23:50
@H-M-H @braunbearded Unfortunately I couldn't use it since I switched to sway and so far I'm unable to share my screen with Wayland.

**Comment by H-M-H** [comment] 2021-02-18 00:51
Alright, I see. I increased the resolution a little with the latest build again but the change shouldn't be too drastic. Closing this for now.

@abdalazizrashid yes unfortunately wayland is not supported yet as screen capturing is a little cumbersome :/

**Closed by H-M-H** 2021-02-18 00:51 UTC
