### ISSUE TITLE
Windows Defender detects newest Release as Virus

### ISSUE THREAD

**Issue by tschuehly** [H-M-H/Weylus#77] opened 2021-03-30 18:29 UTC
![image](https://user-images.githubusercontent.com/33346637/113038232-95d7c580-9196-11eb-9e77-5a3e4a97c8ca.png)

**Comment by H-M-H** [comment] 2021-03-30 18:54
I am not sure what to do about that. Considering that Weylus opens a network connection and indeed lets you remote control your computer it probably looks suspicious to antivirus programs. All I can tell you is that I definitely did not write any evil code to take over your computer. And as Weylus is open source, feel free to check for yourself and build it yourself.

**Comment by tschuehly** [comment] 2021-03-30 20:05
I've opened a case and added you as authorizied user to the case

**Comment by H-M-H** [comment] 2021-03-30 20:12
I can confirm that, I just got mail. Looks like they added it to their queue, lets see how long it takes them to review.

Thanks :)

**Comment by tschuehly** [comment] 2021-03-30 22:40
![Screenshot_20210331-003838~2](https://user-images.githubusercontent.com/33346637/113065754-a3eb0d80-91b9-11eb-9f81-bf70202c0d20.png)
According to the analyst the definition has been removed. I can confirm it tomorrow if it is not being detected anymore.

**Comment by H-M-H** [comment] 2021-03-30 23:24
Excellent! Thanks for your help! Lets hope this does not become a regular thing with every new release.

**Comment by H-M-H** [comment] 2021-04-01 12:07
Closing this for now, as it seems to be resolved.

**Closed by H-M-H** 2021-04-01 12:07 UTC

**Comment by PlaidDroid** [comment] 2021-09-30 10:53
Windows defender still flags the windows build as `Trojan: Script/Oneeva.A!ml`

**Comment by H-M-H** [comment] 2021-09-30 12:00
Oh well, I think instead of *still* flagging Weylus as malware it flags it as malware *again*. I guess this means that every release has to be whitelisted. Anyone with a Microsoft account can submit a request to do that here: https://www.microsoft.com/wdsi/filesubmission
