### ISSUE TITLE
cannot draw on powerpoint

### ISSUE THREAD

**Issue by ericINRAE** [H-M-H/Weylus#40] opened 2020-10-08 08:40 UTC
Hi,
Working on windows10, I can draw on Paint, but sadly, on PowerPoint, it draws only a point at the location I started to touch the tablet with the stylus.

**Comment by H-M-H** [comment] 2020-10-08 13:40
Hello,
Thanks for your feedback, I do not get much insight on how well Weylus runs on Windows!

There are two possible problems that I can think of right now:

- The browser sends unexpected mouse events concerning the buttons pressed
- The library I use to control the mouse does something weird

Please try running the latest version of Weylus: https://github.com/H-M-H/Weylus/suites/1149509854/artifacts/16555003 via your commandline with the environment variable `WEYLUS_LOG_LEVEL=TRACE` to get additional debug messages. Like that I can confirm or rule out the first point in that list. Alternatively if you have access to another computer or device running a recent browser you could try if controlling Weylus with that results in the same problems.

**Comment by ericINRAE** [comment] 2020-10-09 07:42
Hi H-M-H,
Thanks for the quick reply, attached are the logged events when I try to draw on powerpoint.
[log.txt](https://github.com/H-M-H/Weylus/files/5353273/log.txt)

**Comment by H-M-H** [comment] 2020-10-11 20:55
Thanks for the log! Unfortunately it looks like the library I use to create mouse events is acting up. Are you able to compile rust code yourself? To verify that said library is the problem I could write a minimal test program for you to check.

Also, I reopened this as I suspect you did not mean to close this issue.

**Closed** 2020-12-04 19:39 UTC

**Comment by mjdousti** [comment] 2022-03-03 12:02
I also suffer from the same issue. My logged events are similar to those shared by @ericINRAE. Interestingly, I experience this issue in certain apps (e.g., Powerpoint and OneNote) but not the others (e.g., Xournal++ and MS Paint.)

@H-M-H I am willing to test your minimal program. Please let me know what I need to do.

**Comment by H-M-H** [comment] 2022-03-03 12:09
This is being worked on in https://github.com/H-M-H/Weylus/pull/128. Unfortunately I don't have much time at the moment and can't work on Weylus in the next weeks. For now you can try if this experimental build improves things: https://github.com/H-M-H/Weylus/actions/runs/1658407211#artifacts

**Comment by mjdousti** [comment] 2022-03-09 07:41
Thanks for the quick response. I just tried the latest build linked above (v0.11.4) and still faced the same issue.
