### ISSUE TITLE
Wish: Possible to echo what is on the screen?

### ISSUE THREAD

**Issue by tkalfaoglu** [H-M-H/Weylus#63] opened 2021-02-16 08:40 UTC
Perhaps this is already implemented: When I am drawing on the tablet, it shows it on the screen, but the tablet screen stays dark. is it also possible to echo what is on the screen to the tablet? 
When I am drawing, I can't see what I'm drawing unless I keep looking at the screen..

Second question: my palm resting on the tablet prevents me drawing, is that a hardware issue, or is there a quick fix?

I'm a professor and I really like this program and would like to use it in class :)
Many thanks for creating it!

**Comment by H-M-H** [comment] 2021-02-16 09:56
> When I am drawing on the tablet, it shows it on the screen, but the tablet screen stays dark.

This shouldn't be the case, the tablet should always mirror the screen just like it's shown in the GIF in the Readme. It is, however, possible that the browser on your tablet is too old and lacks some APIs to display the video. If you use an Android device the [latest build](https://github.com/H-M-H/Weylus/actions/runs/558461444#artifacts) might fix things already.
To confirm that this is a problem with the tablet, try to connect with another device or the computer Weylus is running itself on and check if the screen is mirrored properly in this case.

> my palm resting on the tablet prevents me drawing, is that a hardware issue, or is there a quick fix?

Possibly there is but it still pretty much depends on hardware. I know that iPads do proper palm rejection if used with a pencil, I am not sure how well Android handles things. If you have a proper stylus/pencil there is a good chance your browser recognizes it as such and in this case you can just disable touch events by unchecking "enable touch" and only events from the stylus/pen will get through.

**Comment by Benjoban** [comment] 2021-03-01 01:58
HI,
I am having the same problem not been able to get a video feed of the screen on a note 20 ultra and on iPad or have the stylus working but a blank screen.
Intel® Core™ i5-7500 CPU @ 3.40GHz × 4, 
NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1) ,
Driver Nvidia-driver-460 (proprietary) , 
running X11/xorg.conf,
Desktop no integrated graphic so I can't have a second screen but shouldn't I be able to get a screen mirror.
Any help would be appreciated.
Ben

**Comment by H-M-H** [comment] 2021-03-01 21:58
Hello @Benjoban, please try the prerelease for v0.10.0: https://github.com/H-M-H/Weylus/releases/tag/v0.10.0-rc1
Like that there should be no problem with all your screens at full resolution as this version of Weylus does do proper down scaling according to the tablet's resolution. Previously Weylus just sent a full resolution video of your screens and apparently your tablet couldn't handle that.

**Comment by guyzis** [comment] 2021-03-06 12:31
Hi @H-M-H I also can't get video mirrored to my android tablet using v0.10.0 you as you suggested (video works fine not in the talbet). I get the following error:

ERROR: Failed to obtain resource, target: [object HTMLVideoElement] type: error src: blob:http://192.168.1.13:1701/3854858b-2a76-451e-b131-223eabf29633 Error object: {"isTrusted":true}
ERROR: http://192.168.1.13:1701/lib.js:L312:31: Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite. Error object: {}

while the 2nd line keep repeating itself.

Any suggestions? :)

**Comment by H-M-H** [comment] 2021-03-06 18:38
Looks like your device can't decode the video stream for some reason. Are you by any chance using VAAPI? What kind of tablet do you use?

**Comment by guyzis** [comment] 2021-03-06 18:48
@H-M-H 
Samsung Tab S6 Lite, get the same errors with VAAPI and without.

**Comment by H-M-H** [comment] 2021-04-01 19:04
The latest build includes an option to reduce the resolution of the video, please check if this solves your problem.

**Comment by guyzis** [comment] 2021-04-04 10:11
nope :(

at FPS(receiving) I see the frame rate changing, but can't see any video on screen.

Also now I sometimes get `WARN: Failed to seek to end of video.`, and sometimes the former error, depends on the source I pick.

**Comment by H-M-H** [comment] 2021-04-05 22:01
What resolution is Weylus encoding the video at?

Perhaps the issue is that Weylus tries to seek to the latest frame too aggressively. You can try if removing video seeking changes things. To do so use the [latest build](https://github.com/H-M-H/Weylus/actions/runs/719223139#artifacts) of Weylus and obtain a copy of the JavaScript code used with `weylus --print-lib-js`, then remove/comment these lines:
```js
        if (video.seekable.length > 0 &&
            // only seek if there is data available, some browsers choke otherwise
            (video.readyState >= 3 ||
                // seek to end if we are more than half a second off, this may happen if a tab is
                // moved to the background
                video.seekable.end(video.seekable.length - 1) - video.currentTime > 0.5)) {
            let seek_time = video.seekable.end(video.seekable.length - 1);
            if (isFinite(seek_time))
                video.currentTime = seek_time;
            else
                log(LogLevel.WARN, "Failed to seek to end of video.");
        }
```

and save the result to a file.

Then run Weylus with `weylus --custom-lib-js path/to/js/file`.

**Comment by H-M-H** [comment] 2021-04-06 13:06
Alternatively check if the video with [this build](https://github.com/H-M-H/Weylus/actions/runs/722595677#artifacts) plays at all.

**Comment by H-M-H** [comment] 2021-04-13 17:04
Has anyone tried the above? I will probably close this issue in favor of opening a new one if this problem persists.

**Comment by guyzis** [comment] 2021-04-13 18:34
The latest build linked [here](https://github.com/H-M-H/Weylus/actions/runs/719223139#artifacts) worked for me!

**Closed** 2021-04-26 15:35 UTC
